services:
  playlist-generator:
    build: .
    volumes:
      - ${HOST_MUSIC_DIR:-./music}:${MUSIC_DIR:-/music}:ro
      - ${OUTPUT_DIR:-./playlists}:/app/playlists
      - ${DB_DIR:-./db}:/app/db  # Database volume
    environment:
      - DB_PATH=/app/db/audio_features.db
    working_dir: /app