services:
  playlist-generator:
    build: .
    volumes:
      - ${MUSIC_DIR:-./music}:/music:ro
      - ${OUTPUT_DIR:-./playlists}:/app/playlists
      - ${CACHE_DIR:-./cache}:/app/cache
    environment:
      - CACHE_DIR=/app/cache
    working_dir: /app