services:
  playlist-generator:
    build: .
    volumes:
      - ${HOST_MUSIC_DIR:-./music}:${MUSIC_DIR:-/music}:ro
      - ${OUTPUT_DIR:-./playlists}:/app/playlists
      - ${CACHE_DIR:-./cache}:/app/cache
    environment:
      - CACHE_DIR=/app/cache
      - TIMEOUT_SECONDS=${TIMEOUT:-30}
      - DB_POOL_SIZE=5
    working_dir: /app
    shm_size: '256mb'
    mem_limit: 2g
    restart: on-failure:3