services:
  playlist-generator:
    build: .
    volumes:
      - music_volume:/music:ro
      - playlists_volume:/app/playlists
      - cache_volume:/app/cache
    environment:
      - CACHE_DIR=/app/cache
    working_dir: /app

volumes:
  music_volume:
    driver_opts:
      type: none
      device: /root/music/library
      o: bind
  playlists_volume:
    driver_opts:
      type: none
      device: ${PWD}/playlists
      o: bind
  cache_volume:
    driver_opts:
      type: none
      device: ${PWD}/cache
      o: bind
