services:
  playlist-generator:
    build: .
    volumes:
      - type: bind
        source: ${MUSIC_DIR}
        target: /music
        read_only: true
      - type: bind
        source: ${OUTPUT_DIR}
        target: /app/playlists
      - type: bind
        source: ${CACHE_DIR}
        target: /app/cache
    environment:
      - CACHE_DIR=/app/cache
    working_dir: /app

# No named volumes needed since we're using bind mounts