version: '3.8'

services:
  playlista-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playlista-test
    volumes:
      - ./test_large_files:/app/test_music:ro
      - ./cache:/app/cache
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    working_dir: /app
    command: >
      sh -c "
        echo 'Starting test analysis of large files...' &&
        python -m src.core.sequential_analyzer /app/test_music/*.mp3 /app/test_music/*.flac /app/test_music/*.ogg /app/test_music/*.m4a
      "
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G 