services:
  playlist-generator:
    build: .
    volumes:
      - ${HOST_MUSIC_DIR:-./music}:${MUSIC_DIR:-/music}:ro
      - ${OUTPUT_DIR:-./playlists}:/app/playlists
      - ${CACHE_DIR:-./cache}:/app/cache
    environment:
      - CACHE_DIR=/app/cache
    working_dir: /app