services:
  playlist-generator:
    build: .
    volumes:
      - ${HOST_MUSIC_DIR:-./music}:/music:ro
      - ${OUTPUT_DIR:-./playlists}:/playlists
      - ${CACHE_DIR:-./cache}:/cache
    environment:
      - WORKERS=${WORKERS:-8}
      - TIMEOUT=${TIMEOUT:-30}