services:
  playlista:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playlista
    volumes:
      # Mount the JSON configuration file
      - /root/music/playlista/config/playlistarrays_config.json:/app/config/playlista_config.json:ro
      # Mount music library
      - /root/music/library:/music:ro
      # Mount output directories
      - /root/music/playlista/cache:/app/cache
      - /root/music/playlista/logs:/app/logs
      - /root/music/playlista/playlists:/app/playlists
      - /root/music/playlista/models:/app/feature_extraction/models
    environment:
      # Only essential environment variables (system paths)
      - PYTHONPATH=/app/src
      # Optional: Override specific settings if needed
      # - MEMORY_LIMIT_GB=8.0
      # - DEBUG=true
    stdin_open: true
    tty: true 