services:
  playlista:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playlista
    volumes:
      - /root/music/library:/music:ro
      - /root/music/playlista/cache:/app/cache
      - /root/music/playlista/logs:/app/logs
      - /root/music/playlista/playlists:/app/playlists
      - /root/music/playlista/models:/app/feature_extraction/models
    environment:
      - PYTHONPATH=/app/src
      - MUSIC_PATH=/music
      - CACHE_DIR=/app/cache
      - LOG_DIR=/app/logs
      - OUTPUT_DIR=/app/playlists
      - MEMORY_LIMIT_GB=6.0
      - MEMORY_AWARE=true
      - HOST_LIBRARY_PATH=/root/music/library
      - LASTFM_API_KEY=9fd1f789ebdf1297e6aa1590a13d85e0
      - LOG_LEVEL=INFO
      - LARGE_FILE_THRESHOLD=50
      - MIN_TRACKS_PER_GENRE=10
    command: ["python", "-m", "src.presentation.cli.main", "--help"]
    stdin_open: true
    tty: true 