services:
  playlista:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playlista
    volumes:
      - ./src:/app/src:ro
      - ./music:/music:ro
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./playlists:/app/playlists
    environment:
      - PYTHONPATH=/app/src
      - MUSIC_PATH=/music
      - CACHE_DIR=/app/cache
      - LOG_DIR=/app/logs
      - OUTPUT_DIR=/app/playlists
      - MEMORY_LIMIT_GB=6.0
      - MEMORY_AWARE=true
    command: ["python", "playlista", "--help"]
    stdin_open: true
    tty: true 