# Docker Compose configuration for Playlist Generator Simple
# All configuration is handled via playlista.conf file

services:
  playlista-simple:
    container_name: playlista-simple
    build: .
    entrypoint: ["playlista"]
    volumes:
      # Music library - mount your music directory here
      - /root/music/library:/music:ro
      
      # Playlists output directory
      - /root/music/library/playlists/auto:/app/playlists
      
      # Cache directory for analysis results
      - /root/music/playlista/cache:/app/cache
      
      # Logs directory
      - /root/music/playlista/logs:/app/logs
      
      # Failed files directory
      - /tmp/failed_files:/app/failed_files
      
      # Models directory (for feature extraction models)
      - /root/music/playlista/models/musicnn:/app/feature_extraction/models/musicnn:ro
      
      # Configuration file
      - /root/music/playlista/playlista.conf:/app/playlista.conf:ro
    working_dir: /app
    tty: true
    stdin_open: true