# Docker Compose configuration for Playlist Generator Simple
# All configuration is handled via playlista.conf file

services:
  playlista-simple:
    container_name: playlista-simple
    build: .
    entrypoint: ["playlista"]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - MUSICBRAINZ_USER_AGENT=${MUSICBRAINZ_USER_AGENT:-playlista-simple/1.0}
      # Color support for Docker containers
      - DOCKER_CONTAINER=true
      - FORCE_COLOR=1
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1
    volumes:
      # Music library - mount your music directory here
      - /root/music/library:/music:ro
      
      # Playlists output directory
      - /root/music/playlista/playlists:/app/playlists
      
      # Cache directory for analysis results
      - /root/music/playlista/cache:/app/cache
      
      # Logs directory
      - /root/music/playlista/logs:/app/logs
            
      # Models directory (for feature extraction models)
      - /root/music/playlista/models/musicnn:/app/models:ro
      
      # Configuration file
      - /root/music/playlista/config/playlista.conf:/app/playlista.conf:ro
    working_dir: /app
    tty: true
    stdin_open: true