services:
  # Playlist Generator Simple
  playlist-generator:
    build: .
    container_name: playlist-generator
    ports:
      - "8501:8500"
    volumes:
      # Music library - mount your music directory here
      - /root/music/library:/music:ro
      
      # Playlists output directory
      - /root/music/playlista/playlists:/app/playlists
      
      # Cache directory for analysis results
      - /root/music/playlista/cache:/app/cache
      
      # Logs directory
      - /root/music/playlista/logs:/app/logs
              
      # Models directory (for feature extraction models)
      - /root/music/playlista/models/musicnn:/app/models:ro
      
      # Configuration file
      - /root/music/playlista/config/playlista.conf:/app/playlista.conf:ro
    environment:
      - PYTHONPATH=/app
      - CACHE_DIR=/app/cache
      - LOG_LEVEL=INFO
      - DOCKER_CONTAINER=true
      - FORCE_COLOR=1
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1
      # TensorFlow warning suppression
      - TF_CPP_MIN_LOG_LEVEL=3
      - TF_ENABLE_ONEDNN_OPTS=0
      - TF_GPU_ALLOCATOR=cpu
      - CUDA_VISIBLE_DEVICES=-1
      # External API keys (set these in your .env file)
      - LASTFM_API_KEY=${LASTFM_API_KEY}
    command: ["/app/entrypoint.sh"]
    restart: unless-stopped
    working_dir: /app
    tty: true
    stdin_open: true