services:
  playlist-generator:
    build: .
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"  # Use host user's UID/GID
    volumes:
      - type: bind
        source: ${MUSIC_DIR}
        target: /music
        read_only: true
      - type: bind
        source: ${OUTPUT_DIR}
        target: /app/playlists
      - type: bind
        source: ${CACHE_DIR}
        target: /app/cache
    environment:
      - CACHE_DIR=/app/cache
      - UID=${CURRENT_UID:-1000}
      - GID=${CURRENT_GID:-1000}
      - PLAYLIST_METHOD=${PLAYLIST_METHOD:-all}
      - MIN_TRACKS_PER_GENRE=${MIN_TRACKS_PER_GENRE:-10}
    working_dir: /app
    command: >
      python main.py
      --music_dir /music
      --host_music_dir ${HOST_MUSIC_DIR}
      --output_dir /app/playlists
      --workers ${WORKERS}
      --num_playlists ${NUM_PLAYLISTS}
      --playlist_method ${PLAYLIST_METHOD}
      ${FORCE_SEQUENTIAL:+--force_sequential}