services:
  playlist-generator:
    build: .
    volumes:
      - type: bind
        source: ${MUSIC_DIR}
        target: /music
        read_only: true
      - type: bind
        source: ${OUTPUT_DIR}
        target: /app/playlists
      - type: bind
        source: ${CACHE_DIR}
        target: /app/cache
    environment:
      - CACHE_DIR=/app/cache
    working_dir: /app
    command: >
      --music_dir /music
      --host_music_dir ${HOST_MUSIC_DIR}
      --output_dir /app/playlists
      --workers ${WORKERS}
      --num_playlists ${NUM_PLAYLISTS}
      ${ANALYZE_ONLY:+--analyze_only}
      ${GENERATE_ONLY:+--generate_only}
      ${FORCE_SEQUENTIAL:+--force_sequential}
      ${UPDATE:+--update}