services:
  audiolizer:
    build: .
    entrypoint: ["audiolizer"]
    volumes:
      - /root/music/library:/music
      - /root/music/library/playlists/auto:/app/playlists
      - /root/music/library/playlists/auto/cache:/app/cache
      - /tmp/failed_files:/app/failed_files
    environment:
      - PLAYLIST_METHOD=${PLAYLIST_METHOD:-all}
      - MIN_TRACKS_PER_GENRE=${MIN_TRACKS_PER_GENRE:-10}
      - LASTFM_API_KEY=9fd1f789ebdf1297e6aa1590a13d85e0
    working_dir: /app
    tty: true
    # NOTE: The host directory /root/music/library/failed_files will store failed files and is excluded from the music scan.
    
