services:
  audiolizer:
    build: .
    user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
    entrypoint: ["audiolizer"]
    volumes:
      - /root/music/library:/music:ro
      - /root/music/library/playlists/auto:/app/playlists
      - /root/music/library/playlists/auto/cache:/app/cache
    environment:
      - UID=${CURRENT_UID:-1000}
      - GID=${CURRENT_GID:-1000}
      - PLAYLIST_METHOD=${PLAYLIST_METHOD:-all}
      - MIN_TRACKS_PER_GENRE=${MIN_TRACKS_PER_GENRE:-10}
    working_dir: /app
    tty: true
    # Service and entrypoint are now named audiolizer